### ISSUE TITLE
Field as String

### ISSUE THREAD

**Issue by firante** [jsep/meteor-facebook-native-login#6]
Seems like facebook wants fields as String not as the array

getIdentity(accessToken) {
    expect(accessToken).to.be.a("string");
    try {
      return HTTP.get(this._apiUri, {
        params: {
          access_token: accessToken,
          fields: this._fields()       // --- like this  fields: this._fields.join() ---
        }
      }).data
    } catch (ex) {
      let err = new Error("Failed to fetch identity from Facebook. " + ex.message);
      err.response = ex.response;
      throw err;
    }
  }

**Comment by v3rron** [comment]
@firante having the same issue with Facebook login after a new production deploy.
```
Exception while invoking method 'login' Error: Failed to fetch identity from Facebook. failed [400] {"error":{"message":"\"fields\" param is not a valid string","type":"OAuthException","code":2500,"fbtrace_id":"G1a6jBB0y1U"}}
at NativeFacebookLoginHandler.getIdentity (packages/gillesmanzato:facebook-native-login/NativeFacebookLoginHandler.js:64:17)
at NativeFacebookLoginHandler.login (packages/gillesmanzato:facebook-native-login/NativeFacebookLoginHandler.js:34:27)
at [object Object].<anonymous> (packages/gillesmanzato:facebook-native-login/NativeFacebookLoginHandler.js:75:23)
at packages/accounts-base/accounts_server.js:468:32
at tryLoginMethod (packages/accounts-base/accounts_server.js:245:14)
at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:465:18)
at [object Object].methods.login (packages/accounts-base/accounts_server.js:528:27)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
at packages/ddp-server/livedata_server.js:719:19
at [object Object].EVp.withValue (packages/meteor.js:1135:15)
```
Did you happen to fix it?

**Comment by pisacode** [comment]
use it like this `params: {
          access_token: accessToken,
          fields: this._fields.join(',')
        }`
